name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:

  - type: textarea
    id: cause
    attributes:
      label: Describe the need of your request
      description: A clear and concise description of what the need or problem is.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
